# Generated by Django 5.0.6 on 2024-07-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_blogcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datetime_first',
            new_name='updated_at',
        ),
    ]
