# Generated by Django 5.0.6 on 2025-01-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_tag_blogcomment_updated_at_post_likes_post_readtime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
