# Generated by Django 5.0.6 on 2025-01-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_post_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
